### ISSUE TITLE
Remove unecessary repositories

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#1]
There are quite a few repositories in the Libretexts org. It isn't clear if all of them are needed for something or are relevant.

- [ ] https://github.com/LibreTexts/custom-docker-deploy (no documentation)
- [x] https://github.com/LibreTexts/the-littlest-Davis (no documentation)
- [ ] https://github.com/LibreTexts/tutorials (no readme)
- [x] https://github.com/LibreTexts/jupyterhub-deploy-teaching
- [ ] https://github.com/LibreTexts/jupyter-python
- [x] https://github.com/LibreTexts/mechmotum.github.io
- [ ] https://github.com/LibreTexts/bqplot
- [ ] https://github.com/LibreTexts/bqplot
- [ ] https://github.com/LibreTexts/pythreejs
- [ ] https://github.com/LibreTexts/jupyter-octave
- [ ] https://github.com/LibreTexts/jupyter-sagemath
- [ ] https://github.com/LibreTexts/jupyter-r

We now have the metalc repo as the primary location for everything we need to get the Jupyterhub/binder setup on the cluster. If any of the other repositories are relevant to the cluster we can either merge or make sure it is clear in the documentation why it needs to be in another repository.

We also need the two repos that were used to run Jupyterhub on a single bare metal server: littlest and deploy-teaching.

Do we need the rest?

Can the @LibreTexts/jupyter-team go through and remove anything we don't need and if we do, make sure the documentation makes it clear what it is for.

**Comment by celine168** [comment]
* https://github.com/LibreTexts/jupyterhub-deploy-teaching is necessary since it contains our test script and updated instructions on installing JupyterHub.
* https://github.com/LibreTexts/mechmotum.github.io; we forked this repository to add blog posts, I believe that we should keep this for future use.
* jupyter-python, bqplot, pytheejs were created before the Jupyter team formed, am personally unsure of their importance.
* jupyter-octave, jupyter-sagemath, and jupyter-r were created before the Jupyter team formed and deal with user environments/kernels, if I remember correctly. @Miniland1333, could you please confirm?
* https://github.com/LibreTexts/tutorials was created to contain tutorials when we started making VMs to run JupyterHub. One of the files is already part of the metalc repo. Kevin's [baremetal_jhub](https://github.com/LibreTexts/tutorials/blob/master/baremetal_jhub.md) contains some instructions installing JupyterHub on a VM from following the jupyterhub-deploy-teaching repo but also has some extra steps on how we got around problems during installing. I do think this file is a valuable reference.
* https://github.com/LibreTexts/the-littlest-Davis should be kept for future reference/customization of the littlest-Davis
* According to Luigi, https://github.com/LibreTexts/custom-docker-deploy could be deleted. We did not focus much of our time to this repo.

**Comment by moorepants** [comment]
Great! Thanks for the info.

Maybe we should merge the tutorials content into baremetalc and delete it?

And deleting custom-docker-deploy sounds fine.

For the rest that the Jupyter team created, they should at least have a readme that explains what you have written above.

Henry can handle any of the others. He maybe be using them with the demo setup.

**Comment by Miniland1333** [comment]
I have deleted bqplot and pthreejs repositories since I have already used the relevant bits of code.

Jupyter-python, Jupyter-R, Jupyter-Octave, and Jupyter-Sagemath are all used in the current demonstration as MyBinder wants a github repo to build from. If you have a suggestion, I can modify the names of these repos somehow to make their usage more apparent.

**Comment by moorepants** [comment]
Thanks @Miniland1333. We're good now.
