### ISSUE TITLE
Docker images taking up space and CPU/RAM

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#116]
Each node pulls the Docker images, which includes the cached layers. `Overlay2` is a process that takes up a lot of disk space and consumes RAM/CPU; [this issue on Stack Overflow](https://stackoverflow.com/questions/46672001/is-it-safe-to-clean-docker-overlay2) is related.

Possible solutions:
- [ ] Run `docker system prune` on the nodes
- [ ] Cleaning up the Dockerfile. Less steps would involve less layers, but the general order of the Dockerfile should be preserved.

**Comment by tkumar98** [comment]
@celine168 I think it may not have to do with the image size, but the scheduling system that allocates nodes to tasks. And this may be occurring when an available low memory node is assigned. It somewhat looked like that was the case when we were trying to do the upgrade on Sunday

**Comment by celine168** [comment]
I will document the current process of resolving the issue.

Each node has continuous-image-pullers, which pull the Docker images from Docker Hub. The images are now pulled when an upgrade is run.
Since the layers of Docker images can take up a lot of space, this can lead to ephemeral storage errors on Kubernetes. The typical solution to resolve this for now is to ssh into the node, run `docker system prune`, and delete `Evicted` pods from rooster as necessary.

**Comment by celine168** [comment]
One solution to solve this is to run a cron job with `docker system prune` every so often.
Its possible consequences would include: 
* a good number of `Evicted` pods would appear in the K8s API. We would have to manually clean these and it's not exactly the most efficient way.
* we can't know if something goes wrong with the cron job until something pops up.

**Comment by moorepants** [comment]
- Can we have images stored on the ZFS instead of each node?
- Prune manually for now
- Avoid images on the low drive space nodes (probably can't happen)
- Figure out kubernets garbarge collector so that not some images are kept around

**Comment by celine168** [comment]
Having images stored on the ZFS:
- Each node has a continuous image puller, which pulls these images onto each node. 
- I know we can create `.yaml` files that could create claims to the NFS server
e.g. 
```apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-persist
spec:
  capacity:
    storage: 123Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-${EFS_ID}.efs.us-east-1.amazonaws.com
    path: "/"
```
- I want to avoid hacking into Jupyterhub directly for this as that does not seem like the optimal solution for me
- Dockerspawner: https://github.com/jupyterhub/dockerspawner

**Comment by celine168** [comment]
Some new info. I noticed that when I run `docker image prune` on a node that's running low on space, it doesn't clear that much data. But running `docker container prune` does clear a good amount of data. 

This especially helps if there are a lot of `Evicted` pods on that particular node. The space issue could be related to Docker images, or the Docker containers pulling the images, or not with the images at all...(am leaning towards the second but need to investigate further).

**Comment by moorepants** [comment]
@rkevin-arch @sandertyu This is another issue with details on the large dockerfiles.

**Comment by moorepants** [comment]
Chicks 11 to 18 have smaller SSD disks. #179

**Comment by moorepants** [comment]
Last week we discussed some things about this. One new info for me was that there are a minimal # of docker images that have to be on each node and these are tied to each kubernetes service, i.e. our default-env image isn't the only one on the nodes. Secondly, Kevin does not believe that it is possible to cache the docker images on the NFS server but it still isnt' super clear if that is absolutely true. We discussed some solutions:

- Do research and determine if we can use the NFS server as the common cache store. If so or if not, report back what you learn (ideally in this issue).
- Buy larger drives for the nodes. To do this, you all need to research what a minimal drive size would be to last us ~5 years. Consider the number of images we may have to host, life of drives, and compatibility with both flock and galaxy. Find some bulk purchase drives that are suitable for our needs and report to us a price.

Those are the current two paths. Both should be looked into.

**Comment by moorepants** [comment]
Also, the high CPU/RAM use comes from the disks running out of space when trying to upgrade.

**Comment by rkevin-arch** [comment]
NFS can be used by docker by mounting `/var/lib/docker` directly from hen, and that would alleviate the disk issue. However, each chick must have its own copy of `/var/lib/docker`, since the docker daemon will manage that directory and store its own state in there, so if we do this we would have 18 copies of the image if all 18 chicks do a `docker pull`. When I said it's impossible to use NFS I was referring to having every chick _share_ the same image, but it is still possible to use hen's storage for `/var/lib/docker` as long as each chick is separate.

As for the "high" CPU/RAM usage, it isn't high usage at all. Prometheus gathers data by having a DaemonSet pod on every node, and if a node doesn't have disk space, kubernetes will start killing pods as a last-ditch effort to save disk space. This causes Prometheus to not get any data from that node, hence triggering the alert.

**Comment by rkevin-arch** [comment]
We have two options. 
1. Mount `/var/lib/docker` on chicks to hen
- Hen has 50+TB of storage, and we're using less than 0.2% of it. This would be way overkill and ensure we would never run out of space again
- Single point of failure. If hen goes down, _all_ nodes stop functioning, and it isn't clear if docker can recover from `/var/lib/docker` itself going completely missing (even when hen is restored, we might have to do manual cleanup)
- Potential performance hit, since accessing literally any file in a container has to go through NFS
2. Buy bigger drives
- Obviously, drives aren't free
- IMO 250GB would be big enough for our current use case if we do `docker system prune` and delete old images regularly. Something like 500GB would be usable. If we decide to pile more work onto the chicks though, we may or may not need bigger disks. IMO 1TB would be really comfortable, but probably a bit overkill. For reference, currently chick3 is using 412G of storage after a `docker prune` (which may have deleted a couple dozen GB of stuff) but not untagging/deleting any used images.

**Comment by moorepants** [comment]
> As for the "high" CPU/RAM usage, it isn't high usage at all. Prometheus gathers data by having a DaemonSet pod on every node, and if a node doesn't have disk space, kubernetes will start killing pods as a last-ditch effort to save disk space. This causes Prometheus to not get any data from that node, hence triggering the alert.

Good to know.

**Comment by moorepants** [comment]
Please research some prices for 1TB drives. Ask Richard if they should be SSD or can be optical.

**Comment by moorepants** [comment]
Give some 500GB prices too. But if chick3 has 412G seems like 500G isn't a good idea for longevity.

**Comment by moorepants** [comment]
For the mount /var/lib/docker option. If we have 18 copies of all images, what amount of space will that be?

**Comment by rkevin-arch** [comment]
BTW, I added this to my earlier comment:
> However, since all our persistent volumes are on hen anyway, this may or may not be a concern since hen is already a single point of failure for all services that need persistent volumes.

> If chick3 has 412G seems like 500G isn't a good idea for longevity.
Technically, we can probably get away with 500. `chick3` has 45 images of `default-test` and 32 images of `default-env`, most of which are old and can be deleted. Each image is like 7GB big, so we can clean most of those up.

> For the mount /var/lib/docker option. If we have 18 copies of all images, what amount of space will that be?
Worst case scenario, assume every chick uses 1TB of `/var/lib/docker` (should never end up happening). That's only 18TB and less than 1/3 of hen's storage.

**Comment by moorepants** [comment]
> Worst case scenario, assume every chick uses 1TB of /var/lib/docker (should never end up happening). That's only 18TB and less than 1/3 of hen's storage.

For now, that is fine. Ask Richard if if thinks using 18TB on hen for the docker images is a good idea. More realistically its going to be less than half of that, right?

**Comment by rkevin-arch** [comment]
I do need to also research whether NFS supports the extended attributes stuff that docker needs if we do go the NFS route. Alternatively, since chicks 0~10 already have enough space, we can just hook 11~18 up to NFS as a trial run, which should take much, much less than 5TB.

**Comment by rkevin-arch** [comment]
Also, Amazon thinks 500GB SSDs are around 60 dollars, and 1TB ones are around 110 dollars. I didn't pick one or dug through read/write speeds, that's just what most SSDs seem to cost.

**Comment by rkevin-arch** [comment]
Some things to keep in mind if we're gonna go the NFS route.

Docker's recommended storage driver for containers is `overlayfs`, but that requires the underlying filesystem to be `ext4` or `xfs`. If we're using NFS, we can only use the `vfs` storage driver, which "is intended for testing purposes, and for situations where no copy-on-write filesystem can be used. Performance of this storage driver is poor, and is not generally recommended for production use." More details [here](https://docs.docker.com/storage/storagedriver/select-storage-driver/#supported-backing-filesystems).

If we're going to use the `vfs` storage driver, since it is not a union filesystem, it has to build the layers by copying the previous layer into a brand new directory, which is both inefficient and costs much more storage, since each layer is copied multiple times. More info [here](https://docs.docker.com/storage/storagedriver/vfs-driver/). Considering some of our images have dozens of layers, this means we might use dozens of times more storage using the `vfs` storage driver.

There might be ways to trick `overlayfs` to work on NFS, but it's not supported in any way and I need to do more research to know if it's even possible.

**Comment by moorepants** [comment]
@rfeltstykket Can you read this info Kevin has provided and give your thoughts?

**Comment by rkevin-arch** [comment]
After a while of digging I found this: https://github.com/moby/moby/pull/35483
Quote:
> The upper filesystem will normally be writable and if it
is it must support the creation of trusted.* extended attributes, and
must provide valid d_type in readdir responses, so NFS is not suitable.

**Comment by rkevin-arch** [comment]
This is the main issue to track the progress for getting new SSDs for all the nodes. The current solution is to remove chick11~18 until the new disks arrive, and since we don't have many users we plan on making these chicks the prototype galaxy cluster instead. Will close this issue once the new SSDs are arrived and installed.

**Comment by sandertyu** [comment]
The SSDs have arrived and they have been installed. We are trying to use chicks11-18 for development on the new Galaxy cluster, so we will leave them removed from Flock, at least for now. Closing the issue.
