### ISSUE TITLE
Rooster update email should be informative

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#122]
This is what it currently displays: `InstCount=0 DelCount=0 BrokenCount=0`

and Rooster is mispelled Rooter.

This email should say something meaningful, like if an update is required or not.

**Comment by narrator0** [comment]
This is the original output from the software we use to check updates. Is doesn't have a proper output or API right now. This line means that there is something to update and a dry-run of it produces no error. Since I can still understand what it means and update it, I find this problem not urgent and focus on developing the plugin for now. I will fix it when we get the MVP of the plugin out.

**Comment by moorepants** [comment]
At least add to our documentation what it means and tell us all. We don't know what it means.

**Comment by moorepants** [comment]
@narrator0 Seems like a quick thing to close this one. Can you document what the output is and close?

**Comment by moorepants** [comment]
Closing this, the email is working.
