### ISSUE TITLE
Some chicks aren't on the latest Ubuntu (18.04.3)

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#131]
See:

```
kubectl get nodes -n jhub -o wide
```

It shows that some are 18.04.2 and some 18.04.3. Shouldn't these all be up-to-date?

**Comment by sandertyu** [comment]
What's the process for updating the Ubuntu operating system on the cluster? I'd like to try and update these, but I don't know what programs are used to update and manage this system.

**Comment by moorepants** [comment]
The basic idea is to ssh into each node. I think you use the kubectl command on the master node (rooster) to then access the other nodes. You can then run the appropriate ubuntu commands to update. But we also have a way to run the command once and have it run on all nodes (I think). @celine168 You'd probably have the best answer. The nodes have to stay on ubuntu 18.04 but could get the minor upgrade safely I think.

**Comment by celine168** [comment]
To get the list of the names of the nodes, you can run `kubectl get nodes`.
To SSH into a node, just run something like `ssh chick1` on rooster. 

My suggestions:
* Test out an upgrade on one of the nodes manually first to make sure that it's okay
* [Cordon the node](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#interacting-with-nodes-and-cluster) before performing the upgrade if you want to be super safe. This means marking the node unschedulable so that no new pods get scheduled on it and current pods get moved elsewhere.
  * Note that `kubectl` commands can only be run from rooster!
```
kubectl cordon my-node                                                # Mark my-node as unschedulable
kubectl drain my-node                                                 # Drain my-node in preparation for maintenance
```
* **Don't cordon/drain chick0.** That's the master node which schedules the rest of the pods on the other child nodes (chick1-chick18), and draining it would probably mess this up. If we really want to upgrade the OS on chick0, we could try to upgrade the OS on another chick without cordoning and see what happens. 
* Updating the OS (I'll add more info here later....work in progress)

After testing out an upgrade manually, you can probably try automating it using Ansible. I can give more information on this a little later :)

**Comment by sandertyu** [comment]
Okay, thank you Celine for the full description. I will try this out this weekend.

**Comment by moorepants** [comment]
@sandertyu Just another word of caution. Anything that you run on the live production servers (this is one of those things) you should feel very confident that what you will do will not take down anything. I recommend doing this along with one of the other students for your first forays into the live system.

**Comment by sandertyu** [comment]
> @sandertyu Just another word of caution. Anything that you run on the live production servers (this is one of those things) you should feel very confident that what you will do will not take down anything. I recommend doing this along with one of the other students for your first forays into the live system.

Yes this would be a good idea. I will do that.

**Comment by sandertyu** [comment]
![status](https://user-images.githubusercontent.com/59950537/85210030-9d0da100-b2f1-11ea-8237-3f5e7cf22e8c.PNG)
Here is the current status of the nodes. All of the chicks except for 0, 1, 5, 10 have been updated to kubelet 1.16.10 and Ubuntu 20.04.4. 

As for updating these remaining nodes, we need an explicit procedure for updating chick0, as that one will cause downtime. Chicks 1 and 10 have some critical processes on them, and 5 is simply unplugged so far as I know.

**Comment by sandertyu** [comment]
This has been completed. Closing.
