### ISSUE TITLE
Users should be able to upload data files to a LibreTexts page and Binder can access them

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#144]
For now you can upload and use wget or curl to download in a cell. But it would be nice if those files were automatically loaded into the instance of binder that is opened so wget/curl isn't needed.

- [x] Add a tutorial to show how to wget/curl data files.
- [ ] Look into more advanced connection without wget/curl

**Comment by Miniland1333** [comment]
If you want to import all files that are attached to the current page, this Mindtouch API may be relevant to list them:
https://success.mindtouch.com/Integrations/API/API_Calls/pages/pages%2F%2F%7Bpageid%7D%2F%2Ffiles_(GET)

**Comment by tannavee** [comment]
didn't use wget or curl, but [specific commands](https://chem.libretexts.org/Sandboxes/jupyterteam@ucdavis.edu/CKEditor_Binder_Plugin_Tutorial) related to the languages

**Comment by Miniland1333** [comment]
My guess about his second point about "without wget/curl" is that the attached files should be loaded into the binder filesystem behind-the-scenes so that users don't have to use these web api calls.

As an example, a data file would appear at `./data.csv` and in python you could use `file = open(“testfile.text”, “r”)`.

Various options for accomplishing this include:

1. Compiling the files into the binder during build
2. Have the plugin generate the boilerplate code automatically through a GUI
3. Download and inject into the file system while the binder is warming up

**Comment by tannavee** [comment]
those definitely sound like great ideas, we should have something like that implemented soon.

**Comment by Miniland1333** [comment]
Accomplishing Method 3 is my favorite since it is the most natural for end-users, but I am unsure if you have the leverage into the Thebelab-binder interaction to do so.

1. http://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyter/notebook/master/notebook/services/api/api.yaml#/contents/put_api_contents__path_
2. https://github.com/jupyterlab/jupyterlab/blob/b58c2c545586cd8ed33bb2e1b40e1823e61879cf/packages/services/examples/browser/src/contents.ts

The **@jupyterlab/services** API that Thebelab uses does seem to have a possibly relevant contents API call that I think you should look into. PUT /api/contents/{path}.

------------------------------------------------------------
I have a fourth suggestion which I also find acceptable:
4. In conjunction with 2., build language-specific abstraction functions that load a remote file into the filesystem.
`downloadFile('data.txt')`
This hides the logic for the users but still makes it explicitly clear what files are being loaded into the filesystem.

If you have any questions you'd like to ask me, I have enough time to attend tomorrow's meeting.

**Comment by moorepants** [comment]
The gitpuller tool does something similar to some of these ideas. We should be able to make this pull the data automatically on build.

**Comment by celine168** [comment]
Somewhat relevant issue: https://github.com/minrk/thebelab/issues/43
This is before we connect to the kernel though.
```let cells = thebelab.renderAllCells();
thebelab
  .requestKernel(kernelOptions)
  .then(function(kernel) {
    kernel
      .requestExecute({code: "my_initialize"})
      .then(function () {
        thebelab.hookupKernel(kernel, cells)
      });
  });
```

**Comment by moorepants** [comment]
I think that we can close this. The wget and urlib type solutions should be sufficient. This can be reopened if libretexts users need something more advanced in the future. #156 is a sufficient solution.
