### ISSUE TITLE
How to access data section of tutorial needs improvement.

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#156]
https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)

If I run the Python example I get this error:

```
https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)
```

The Julia example just has "println()" in it.

There are no instructions about how you should upload a file.

There is no bash example which would work in any language:

```
!curl http://somthing.org/data.file
```
or
```
!wget http://somthing.org/data.file
```

Do the links need the `?origin=mt-web` part? Probably not.

I think a better tutorial would be to have a page for each language with a data file uploaded to that page. Then you can have a cell that downloads the data using wget or curl AND examples using different language features. For Python, for example, you can get the file using the builtin url library, pandas, numpy probably, etc.

**Comment by moorepants** [comment]
@tannavee Richard and I met with Delmar today and this was not in a super useful state for Delmar to understand what to do (not us).

**Comment by tannavee** [comment]
I’m currently trying to see if files uploaded to the page can be automatically available in binder, hopefully that will make it less complicated

**Comment by moorepants** [comment]
That's fine, but we should have working instructions until that is ready.

**Comment by tannavee** [comment]
@moorepants I believe you may have been getting the error because currently the LibreTexts pages can only support on language, and all the languages are on the tutorial page. 

I tested out the Python Code on a separate page I made, and everything looks good to me. 

![image](https://user-images.githubusercontent.com/53124295/81874798-91310100-9533-11ea-83f8-67c02c318188.png)

**Comment by tannavee** [comment]
I have also made some additions to the page, if there is anything else I can add to make it clearer, please let me know. 

![image](https://user-images.githubusercontent.com/53124295/81875031-2c29db00-9534-11ea-850e-583f61738256.png)
![image](https://user-images.githubusercontent.com/53124295/81875064-4794e600-9534-11ea-8c03-3e1ea18a14a1.png)

**Comment by tannavee** [comment]
I think having separate pages is a good idea, so I am working on linking them to the current tutorial page.

**Comment by moorepants** [comment]
> I believe you may have been getting the Python error because currently one LibreTexts page can only support one language, and all the languages are on the tutorial page. I just added the different languages for the sake of the tutorial.

That's a good explanation, but a reader of the tutorial will not understand why the code does not work.

**Comment by tannavee** [comment]
I have added the links to these separate pages on the main tutorial, but the links won't work until the pages have been added in the proper location (I have emailed Delmar about this so hopefully that can be fixed soon).

Main tutorial page: https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)

Python: https://chem.libretexts.org/Sandboxes/jupyterteam@ucdavis.edu/How_to_Incorporate_Data_Files_in_Your_Code_Blocks%3A_For_Python

R: 
https://chem.libretexts.org/Sandboxes/jupyterteam@ucdavis.edu/How_to_Incorporate_Data_Files_in_Your_Code_Blocks%3A_For_Python/How_to_Incorporate_Data_Files_in_Your_Code_Blocks%3A_For_R

Julia: 
https://chem.libretexts.org/Sandboxes/jupyterteam@ucdavis.edu/How_to_Incorporate_Data_Files_in_Your_Code_Blocks%3A_For_Julia

C++: 
https://chem.libretexts.org/Sandboxes/jupyterteam@ucdavis.edu/How_to_Incorporate_Data_Files_in_Your_Code_Blocks%3A_For_C

For SageMath it seems that the binder in which we are pointing to does not support wget, because when running !wget, we an error. I'm currently not sure if we should consider creating our own environment.

![image](https://user-images.githubusercontent.com/53124295/82178735-8e1a7580-9891-11ea-9a7d-e7c422418074.png)

**Comment by moorepants** [comment]
You could try curl, maybe it is installed.

**Comment by moorepants** [comment]
These are looking great! We can discuss today.

**Comment by tannavee** [comment]
I realized I forgot to include the Octave link:
https://chem.libretexts.org/Sandboxes/jupyterteam@ucdavis.edu/How_to_Incorporate_Data_Files_in_Your_Code_Blocks%3A_For_Octave

Updated SageMath error:
![image](https://user-images.githubusercontent.com/53124295/82252327-ab882780-9903-11ea-9c9c-f48d54ce634e.png)

**Comment by moorepants** [comment]
This all looks good. We gave a few comments in the meeting. Once those are addressed we can close this. Thanks!

**Comment by tannavee** [comment]
Fixed format for R
![image](https://user-images.githubusercontent.com/53124295/82838379-e39de600-9e80-11ea-89b3-cf372a655cb6.png)

Finalized tutorial for Sage:
![image](https://user-images.githubusercontent.com/53124295/82839292-c0c10100-9e83-11ea-9e44-890fe19effec.png)

Fixed broken URLs on main page:
https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)

**Comment by moorepants** [comment]
I just check them all out and they look good!

The only remaining thing is octave. You have "For Octave:" on the main page but nothing there.

Octave should be able to run wget using this: https://superuser.com/questions/363758/how-do-i-run-a-linux-shell-command-from-octave

`system('wget ..')`

**Comment by tannavee** [comment]
oops forgot to mention, the page is already created, just waiting for Delmar to transfer it to the right place

**Comment by moorepants** [comment]
I think it would be worth adding the `system()` call also. All these languages usually have a way to make system calls.

**Comment by Miniland1333** [comment]
> oops forgot to mention, the page for Octave is already created, just waiting for Delmar to transfer it to the right place
> 
> https://chem.libretexts.org/Sandboxes/jupyterteam@ucdavis.edu/How_to_Incorporate_Data_Files_in_Your_Code_Blocks%3A_For_Octave

Do you need me to make this page public?

**Comment by moorepants** [comment]
Henry, where can we learn how to use LibreTexts as a page/book author? For example, I don't understand why we need others to make things public or why we can't put the pages where we want?

Is there a tutorial we should take or watch to understand how LibreTexts authoring works?

**Comment by Miniland1333** [comment]
It looks like that account already has the permissions to making things public and move pages around. I asked for that page since neither JupyterTeam nor Delmar had made the page public yet. My guess is that y'all were having Delmar move the content to its proper place since he knows where it should go in the construction guide.

In the options menu, you already have access to the Restrict Access (Change Permissions) and Move capabilities:
![image](https://user-images.githubusercontent.com/12994749/82845080-e0fabb00-9e97-11ea-8c31-466cbd8e7ae6.png)

In the restrict access, you can change the page privacy to public:
![image](https://user-images.githubusercontent.com/12994749/82845236-99c0fa00-9e98-11ea-9a72-f06167f26374.png)


FYI, one of the priorities for summer will be to gut/simplify the permissions system on LibreTexts. A part of this will involve abstracting permissions away for users since the current system has been a continual source of confusion and security issues. We will create a tutorial once this new permissions workflow is in place.

**Comment by moorepants** [comment]
That all sounds good, but is there a tutorial where we can learn all this kind of stuff?

**Comment by Miniland1333** [comment]
Delmar doesn't think we have anything written down for this higher level stuff. Since so few people work with this higher-level functionality, Delmar usually does one-on-one/small group training.

In the meantime, direct emails at Delmar and I so that we can provide assistance.

Once we finish gutting/simplifying these permissions systems in the summer, we will be able to create tutorials for this new system.

**Comment by moorepants** [comment]
I'm not talking about high level stuff. How are the student content editor army trained? I thought there was some training for that?

**Comment by Miniland1333** [comment]
Based on feedback from Delmar, the written training materials are located in the [Construction Guide](https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide). If there is anything that you need that isn't covered in there, let us know.

**Comment by moorepants** [comment]
Thanks!

**Comment by moorepants** [comment]
Yes, that's exactly what I was looking for.
