### ISSUE TITLE
Automate Kubernetes Certificate Renewal 

### ISSUE THREAD

**Issue by tannavee** [LibreTexts/metalc#159]
The certificates expire after one year, and currently renewals are manual. Automating this will prevent the cluster from going down unexpectedly. 

Link: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#automatic-certificate-renewal

**Comment by rkevin-arch** [comment]
IMO, we shouldn't automate certificate renewal. They will be automatically renewed when we upgrade the control plane, and we should probably do that routinely anyway. If we don't wait an entire year between control plane upgrades, certificate renewal isn't a problem.

**Comment by rkevin-arch** [comment]
Discussed with Noah a while ago, and we both think having our cluster upgrade more often than yearly would be ideal for security (and downtime can be schedule during breaks to not interrupt most users). In that case, certificate renewal shouldn't be an issue.

**Comment by moorepants** [comment]
I'd like to address this better than the suggestion as it took down the whole cluster during exam week last time.

**Comment by sandertyu** [comment]
> I'd like to address this better than the suggestion as it took down the whole cluster during exam week last time.

Based on the documentation posted above, kubernetes seems to really suggest that the control plane is upgrade fairly frequently. In the odd case that this happens again, could we maybe automatically send out a notice or email before the certs expire if the control plane hasn't been upgraded within a year? Alternatively, we could try and auto-upgrade (probably risky because upgrades can be messy) or do a "manual" cert renewal through our automated process whenever it approaches a year without an upgrade.

**Comment by moorepants** [comment]
If the solution is to upgrade something manually more often, then we need to add it to our maintenance documention. We need some kind of system to make sure things happen if they need to be done manually. This could be an always open issue with checkboxes for dates or a set of milestones, etc. Whatever the solution is it needs to be formalized so that you all, us, or the next student employees know what to do and when to do it.

**Comment by rkevin-arch** [comment]
I've added some documentation in #186, along with a cronjob that sends out an email 3 times a year. That email looks like this currently:
> Subject: Flock cluster control plane upgrade reminder

> This is a triyearly reminder to check for upgrades to the Kubernetes control plane. The current control plane version is v1.18.5.
> You should definitely search online and see if a newer version is available. If not, you should follow the guide in https://github.com/LibreTexts/metalc/blob/master/docs/maintenance-tasks.md#cluster-control-plane-upgrade and upgrade the control plane.
> Note that if this isn't done regularly, the Kubernetes certificates may EXPIRE and BRING OUR ENTIRE CLUSTER DOWN. This is hard to recover from, so please make sure you upgrade the cluster or at least follow the certificate renewal guide in the document before this happens.
> The certificates will expire at Jun 11 23:52:34 2021 GMT.

**Comment by moorepants** [comment]
LGTM
