### ISSUE TITLE
Automate Monthly Scrub Checks on Hen (ZFS) using cron

### ISSUE THREAD

**Issue by tannavee** [LibreTexts/metalc#165]

**Comment by rkevin-arch** [comment]
Update: the monthly email cronjob that checks scrubbing status worked, but starting the automated scrubbing didn't:
```
Jul 01 08:00:01 hen CROND[2193]: (root) CMD (zpool scrub nest)
Jul 01 08:00:01 hen CROND[2171]: (root) CMDOUT (/bin/sh: zpool: command not found)
```
 It's an easy fix though, just change the crontab from `0 8 1 * * zpool scrub nest` to `0 8 1 * * /usr/sbin/zpool scrub nest`.

On another note, for some reason hen is running on EDT, so it's 3 hours ahead of everyone else. It's fine, since the scrub cronjob would run before the email cronjob, but not sure if this is an issue that should be of concern. We can use the current downtime to change the timezone (better now than later), and I'll ask Jason about it.
