### ISSUE TITLE
Jupyterhub returning 405 for HEAD requests

### ISSUE THREAD

**Issue by Miniland1333** [LibreTexts/metalc#178]
For [statuspage monitoring](https://status2.libretexts.org/), the uptime service uses HEAD Requests to test the endpoints.

However, the following endpoints currently return HTTP Error 405 for HEAD requests:
https://jupyter.libretexts.org/hub/login
https://staging.jupyter.libretexts.org/hub/login
https://binder.libretexts.org/

The fix would either be to set up a dedicated path such as /ping or /heartbeat that will allow for HEAD requests or to allow for HEAD requests on these sites universally. The most important aspect is that whatever url is being checked must be representative of the system health.

**Comment by Miniland1333** [comment]
@rkevin-arch and @sandertyu, have you had a chance to look at this issue?

The main goal is that I need some HTTPS endpoints on your jupyter services that is indicative of the service health and accepts HEAD requests. The urls I mentioned previously may work, or if there is some sort of /health endpoint I can connect to that uses HTTP status codes to indicate site health.

Let me know if you have any questions! The new status page should hopefully be up next week.

**Comment by rkevin-arch** [comment]
There is a designated health endpoint, but it too doesn't support HEAD requests. AFAIK there is no workaround rather than modify JupyterHub itself and the webserver it's using, which is very unfortunate. We can add custom services that do respond to HEAD requests, but then you would be monitoring the health of the proxy and the custom service, not the hub itself. Unfortunately I don't see a way around this issue other than forking JupyterHub and making our own custom changes. I'll look a bit more into it and see if there's another way, though.

**Comment by Miniland1333** [comment]
Since these are HTTP requests, one option is to somehow modify the NGINX config to convert incoming HEAD requests internally to GET requests, since the only difference between HEAD and GET is that the caller doesn’t need the GET body.

If that doesn’t work, an alternative that is less desirable is to develop a simple proxy application that intakes HEAD, makes a GET to Jupyter, and then returns the headers.

I’ve submitted an issue to the status page if they are able to implement GET handling, but don’t hold your breath since it may increase their load.

-Henry

**Comment by rkevin-arch** [comment]
I can't find any documentation for nginx, traefik, or configurable-http-proxy to rewrite method types. HAProxy seems to have the ability to rewrite method types, but we aren't using it and adding it to this already volatile chain of reverse proxies doesn't seem like a good idea. The best thing I can think of is to use extra "config" files and override some functions of JupyterHub to patch in support for HEAD requests on that particular health endpoint. This is janky and prone to failure during upgrades (in case they change internals) but seems to be the best solution.

**Comment by rkevin-arch** [comment]
For Binder, things are much more complicated since they don't expose any configurable options for adding endpoints, and their health check is also more complicated than JupyterHub's. Honestly, I think the best way to handle this is to
1. Add a PR to BinderHub (and JupyterHub if we want) to add HEAD support to the health endpoints, wait for it to be merged to master and released (might take a while)
2. Ask the status page provider to support GET requests (IMO the best option, but might also take a while)
3. Add an extra HAProxy middleware that only rewrites HEAD to GET (adding more complexity and more points of failure)
Let us know which option you like the most

**Comment by moorepants** [comment]
@rkevin-arch Can you link to the PRs to jupyter/binder here for reference?

**Comment by rkevin-arch** [comment]
https://github.com/jupyterhub/binderhub/pull/1137
https://github.com/jupyterhub/jupyterhub/pull/3131

**Comment by rkevin-arch** [comment]
Poked at the two PRs since it's been two weeks, and we do want to use binderhub at some point.

**Comment by rkevin-arch** [comment]
Both PRs have been merged. If we want to, we can update JupyterHub/BinderHub to be master and we can use those HEAD requests. Alternatively we can wait for a stable release. @Miniland1333 What do you think?

**Comment by moorepants** [comment]
I think we should stick to stable releases on production, but you can do master on staging, which could help us see bugs earlier.

**Comment by Miniland1333** [comment]
I'm fine with waiting for stable since the statuspage is coming along at the speed of the bureaucracy. (I've been waiting for two months).

**Comment by rkevin-arch** [comment]
Cool, although the health endpoints are all available on production now so you can use them immediately:
- Binder: https://binder.libretexts.org/health, available because we upgraded to a later version (binder doesn't have a stable version, and the official mybinder.org tracks master very closely, so I figured it's fine
- Production and Staging JupyterHub: https://staging.jupyter.libretexts.org/hub/health2 and https://staging.jupyter.libretexts.org/hub/health2: Added via a custom handler in config.yaml, no need to wait for a stable release (once a stable release is made, we can switch over from `health2` to `health`)

In other news, I've made a discord bot to automatically probe the above three endpoints (and Grafana) and sends out a message to me and Noah when something is down. I'm checking every 30s so we should know immediately if something is wrong. It's not the best solution since the bot is running in my apartment and could go down due to a power outage, but it's a lot better than nothing.

**Comment by rkevin-arch** [comment]
This has been fixed for a while now. Closing
