### ISSUE TITLE
Not clear that Julia kernel is working on LIbreTexts

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#191]
When I press run in the first cell of this page:

https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/5.2.02%3A_How_to_Incorporate_Data_Files_in_Your_Code_Blocks-_For_Julia

it says "waiting for kernel..." and never seems to return output. I've waited 5 minutes.

**Comment by moorepants** [comment]
This page also seems to hang:

https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Book%3A_Visual_Statistics_Use_R_(Shipunov)/03%3A_Types_of_Data/3.09%3A_Answers_to_exercises

No output for hours.

**Comment by sandertyu** [comment]
Yes I am seeing the same thing, the Julia kernel seems to be be broken on LibreTexts, but running the same code on our JupyterHub works fine.

error output
![error output](https://cdn.discordapp.com/attachments/387895582733369346/758815306713399336/unknown.png)

The second page there is the R textbook that we reached out to the professor about. We found that it was not added by them and also has a lot of breaking changes due to the move from R 3.6 to R 4.0, so weird behavior is probably to be expected.

**Comment by rkevin-arch** [comment]
![image](https://user-images.githubusercontent.com/5837628/94219297-5b196b80-fe9b-11ea-9bd0-071856c4518a.png)

**Comment by rkevin-arch** [comment]
Oh wait, @sandertyu already made the relevant changes, hold on

**Comment by moorepants** [comment]
The R book should work and at least return an error message.

**Comment by rkevin-arch** [comment]
Confusingly enough, this looks nothing like the ckeditor-binder-plugin we have in the master branch. There seems to be a [jupyter.js](https://awesomefiles.libretexts.org/Jupyter/Jupyter.js) that loads this stuff and seems to not involve ckeditor-binder-plugin at all. Searching for some code pieces in there (such as "jupyter-r") in our organization shows that whatever this code is, it is not on github.
![image](https://user-images.githubusercontent.com/5837628/94233720-32a26900-febd-11ea-9cf1-8570c5b89858.png)
![image](https://user-images.githubusercontent.com/5837628/94234100-d7bd4180-febd-11ea-800f-e307a9e9f1cd.png)

@Miniland1333 Any idea what's going on here?

**Comment by Miniland1333** [comment]
I have just disabled that legacy code for the R book and on Stats/Bookshelves. I will plan on searching through all the libraries tomorrow and disabling any other residual legacy instances. This was a proof-of-concept from a few years ago so that Delmar could demonstrate for grants how Jupyter could integrate with LibreTexts.

This was supposed to have been taken care of when we were migrating off of MyBinder to the local cluster, but of course we are only getting around to that right now. The underlying code has already been long removed from our Github repo, but the files apparently still exist on the production server.

**Comment by rkevin-arch** [comment]
It works now!
![image](https://user-images.githubusercontent.com/5837628/94235372-4bf8e480-fec0-11ea-8eb5-47b8e214a511.png)
What you said also makes sense since some sites has that yellow starting notification in one corner while some other sites don't. We should probably make sure that every site is using the same code, since it would be a maintainability nightmare otherwise.

**Comment by Miniland1333** [comment]
I have whipped up some Regex that is able to convert the older format to the modern one:
Find `/<p class="mt-script-comment">Jupyter Code<\/p>\n\n<pre class="script">\n&lt;pre \('data-jupyter'\)=&quot;true&quot;&gt;'([\s\S]*?)'&lt;\/pre&gt;<\/pre>/`
Replace: `<div class="thebelab-widget"> <pre data-executable="true" data-language="python">$1</pre></div>`

Proof of concept: https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Book%3A_Visual_Statistics_Use_R_(Shipunov)/03%3A_Types_of_Data/3.09%3A_Answers_to_exercises. 

This allows me to partially automate the conversion as long as I know the language. I will continue to look for and convert any legacy code blocks that I find today, but in the future if you find any more that I missed just send me an email with a list of links and the language(s) that need replacing in each link.

**Comment by Miniland1333** [comment]
As of 20/25/9 @ 10:17, all known instances have been converted over.

**Comment by sandertyu** [comment]
Everything is operational now and the R textbook works properly now. Should be safe to close.

**Comment by moorepants** [comment]
@Miniland1333 Thanks for the help here.

I tried the R book now and the first cells work, but other cells depend on files. See:

![Selection_743](https://user-images.githubusercontent.com/276007/94331539-82705580-ffcd-11ea-825b-0b09f5b5f9a1.png)

The students making these books need to make sure the code actually runs.

**Comment by moorepants** [comment]
Also. there seems to be duplicates of most code cells.

**Comment by moorepants** [comment]
Note too that the cells have headers that say "Python". Not sure why that is. This book is pretty broken and confusing, even with binder working. Not sure that's the quality LibreTexts is hoping for, but does seem like a symptom of the actual author not being the maintainer.
