### ISSUE TITLE
Migrate flock to galaxy

### ISSUE THREAD

**Issue by narrator0** [LibreTexts/metalc#198]
Our plan is to move from flock to galaxy in the winter break. As multiple members will be leaving, we will need a complete guide on how any person can accomplish this task. We need to make sure that all data are preserved in this process.

**Comment by moorepants** [comment]
Multiple members is news to me. Who besides Kevin is planning to stop?

**Comment by celine168** [comment]
At the moment I am planning on leaving because I'm graduating after this quarter. I'm sorry, I thought I did mention it before but I must have not.

I am available at least the first few weeks of the next quarter so I could help out a bit then.

**Comment by moorepants** [comment]
@celine168 Ok, congrats! You may have told me and I forgot. All good to know.

**Comment by rkevin-arch** [comment]
Tentative TODO list (approx in order):
- alert downtime
- backup PV/PVCs according to plan
- delete old kubernetes cluster (kubeadm reset) / power down all nodes
- use IPMI to reinstall OS on all nodes (ubuntu 20.04) (keep rooster powered because it's still the gateway / samba server / DHCP server)
- if we don't have a DHCP server anymore, hardcode IPs on all nodes
- shutdown rooster
- rewire nodes according to new network diagram (still work in progress)
- boot up nodes and set up puppet
- Do a puppet run to bootstrap cluster
- Apply migrated PV/PVCs and all k8s objects in our control repo
- Change DNS records for all of our services to point to new ingress
- Test and done [?

**Comment by rkevin-arch** [comment]
Pinning this issue so it's always on top of the issues page. Will unpin once migration is done.

**Comment by moorepants** [comment]
Seems like this issue and #14 are sorta duplicates? Should we close one? This one?

**Comment by sandertyu** [comment]
Yeah I'd say this is fine to close. All relevant information has been put in other issues, and the migration in itself is done I would say.
