### ISSUE TITLE
Install tidycensus (or at least its dependencies)

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#204]
I think we need:

- https://github.com/conda-forge/r-rgdal-feedstock
- https://github.com/conda-forge/r-maptools-feedstock

It also relies on tigris, but I don't see a feedstock for that. I know for sure rgdal is probably a bit harder to install because it needs to be compiled and linked against gdal. So maybe adding it and maptools will be sufficient for `install.packages('tidycensus')` to work.

cc @sandertyu @lindsaypoirier

**Comment by sandertyu** [comment]
I believe building an environment with your suggestion worked. There is an environment with `r-rgdal` and `r-maptools` on [staging of default-env](https://github.com/LibreTexts/default-env/blob/staging/environment.yml) and running `install.packages("tidycensus")` correctly installs the package. I verified that it was available by running `library("tidycensus")`. Once this is deployed to master, all that the students will need to do is type `installl.packages("tidycensus")` into their r-notebook or terminal. I doubt that this is persistent though, and I'm not exactly sure how to make it persist because it is not through a conda environment.

**Comment by moorepants** [comment]
If it isn't persistent, then they can just install again.

Did you get the same errors I did? If so, they don't affect anything?

**Comment by sandertyu** [comment]
If I try to install `tidycensus` on the current 2.1.1 image, I get errors about `tigris`, `r-rgdal` and `r-maptools`. I then created an `environment.yml` with the latter two packages included and then built it with mamba locally. Then I opened a local jupyter notebook through this environment, and running `install.packages("tidycensus")` there worked. 

Currently also building an image and I'll test it there too.

**Comment by moorepants** [comment]
I see. We could recommend that to her, but if we can add the packages to default-env that we can, then that makes it a bit easier.

**Comment by sandertyu** [comment]
`r-rgdal` and `r-maptools` have been added and tested on staging, and here is the [PR](https://github.com/LibreTexts/default-env/pull/53). All that students will have to do is open an r notebook or console and run `install.packages('tidycensus')` and it will be made available to them within that specific pod session. Students will need to run this command every time their server restarts because the package does not persist. They will also need to obtain an API key as outlined [here](https://walker-data.com/tidycensus/articles/basic-usage.html).

**Comment by lindsaypoirier** [comment]
Thank you all for your help on this!

**Comment by moorepants** [comment]
Is this fixed now? (at least in that install.packages('tidycensus') works?)

**Comment by rkevin-arch** [comment]
Noah said this is safe to close.
