### ISSUE TITLE
Setup and configure the second router for the high availability setup

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#220]
We currently have 1 machine for the router/firewall and we saw it fail last week, taking down everything. We need to get the second, redundant, machine setup so that we have high availability.

**Comment by moorepants** [comment]
Here is the tutorial Richard gave us: https://docs.freebsd.org/en/books/handbook/advanced-networking/#carp

**Comment by sandertyu** [comment]
The router is setup with a public IP (128.120.136.61) but does not have high availability at the moment. We can setup HAproxy, DNS, pf and DHCP on our own and they will not actually perform anything for now. There will be a small bit of downtown when we switch it into high availability production with the current firewall, and this will need to be worked out with Richard et al.

**Comment by sandertyu** [comment]
Task list for things we can do on our own;

- [ ] Set up HAproxy
- [ ] Set up DHCP
- [ ] Set up DNS
- [ ] Set up pf

We won't be able to test the services above until we setup high availability between fw2 and fw1. We may have to make some changes to the previous services to get them to work together properly. For now, we can mostly direclty copy the files from fw1 and follow the router configuration guide in the control repo.

The following will need to be done during scheduled downtime and the specifics are subject to change;

- [ ] Set up CARP on both routers for high availability, also test it
- [ ] Move the public IPs on fw1 to a different interface so that the HPC network can use the 10gb interface

**Comment by sandertyu** [comment]
Things that remain to be done:

 - Recable fw1 so the cable inn cxgbe1 will be on em1
 - Plug an ipmi cable (on em0 on fw1) into em0 on fw2
 - Modify rc.conf on each router so that addresses are on the right interface (uncomment and delete some stuff) and test CARP
  - finish the BIND setup for DNS (run startup script `/usr/local/etc/rc.d/named`)

**Comment by sandertyu** [comment]
The routers have both been set up, and each of them are in production, but we will need to keep an active eye on it. For some reason, CARP is preforming incomplete MASTER/BACKUP failovers, and that's causing some issues. Mike suggests that we need to set up preempt and possibly a skew as well so that CARP properly transitions. Herre are some related docs;

https://www.openbsd.org/faq/pf/carp.html#failover

**Comment by sandertyu** [comment]
The failover works consistently and correctly now. I set fw1 to be the preferred master router, and fw2 will become master only when fw1 is unreachable. The cxgbe0 still takes longer to failover; after fw1 comes back online, all of its interfaces will be master (correct), but cxgbe0 on fw2 still reads master for a bit. It consistently changes to backup within about 15 seconds though, so I would say that high availability is working properly now.

Some future considerations are pfsync (mentioned in docs directly above) so that users do not lose their connections during router failover, and possibly making HAproxy [highly available](https://www.digitalocean.com/community/tutorials/how-to-set-up-highly-available-haproxy-servers-with-keepalived-and-floating-ips-on-ubuntu-14-04
) (although I don't think this is necessary). I'm also working on docs right now.
