### ISSUE TITLE
We need some way to make sure the cache is updated with the latest default-env on all nodes

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#250]
Seems like we are having long build times via binder sometimes. Seems like default-env is not cached on some nodes. We need a way to flush and refresh the caches on all nodes after updating default-env.

**Comment by TimStewartJ** [comment]
It turns out that when a new image is applied to the jhub/staging-jhub configuration. it's is pulled onto all of the nodes. Therefore, it seems like the solution to this is simply put the image on either jhub to get it pulled for binderhub to use. I don't think any further solutions would be necessary.
