### ISSUE TITLE
Setup a redundant rooster

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#33]
Richard mentioned that we should probably have redundant master nodes so that if one goes down we are still live. We need to investigate how to do this and get it setup.

**Comment by celine168** [comment]
We discussed the HAProxy and wanted to clear up some confusion.

A combination of few pods run JupyterHub: `hub-<random-string>`, `proxy-<random-string>`, and `auto-https-<random-string>`.  If these pods disappear, the cluster automatically recreates them. Unless if you happen to manually delete a service,  alter the settings of the pods themselves (you would need access to rooster to do this), or all servers get overloaded, we don't think there is a way for JupyterHub to go down from this end.

Right now, rooster receives traffic and forwards it to the cluster IPs. Most examples of HAProxy seem to redirect traffic to several backend servers (which are running the same service in case if one server goes down); for us, we redirect traffic to specific services in the cluster. In the former, if one server goes down, then HAProxy will choose another server that is up. In our setup, we already have pods that run JupyterHub that could restart themselves if they disappear. 

That being said, we only have one master (single point of failure). If the master node goes down, then the pods can't be scheduled (aka this is very bad). If we have multiple master nodes with rooster running HAProxy, then this could be avoided; however, we think that rooster would still serve as a single point of failure since it is a) the only node connected to the internet, and b) it is the proxy.

Another option is to set up a new server specifically for running HAProxy and leave rooster solely as a management node. However, that new server will still serve as a single point of failure.

We would rather have more time to test HAProxy on a staging cluster and implement it in a future production cluster, since we only have six days left. Even though HAProxy is said to be more efficient than NGINX, we think that rooster can handle traffic fine for now.

One more clarification: rooster is a management node, not the master node. chick0 is the master node.

We can discuss this over video chat if you wish; this may be a little confusing.

**Comment by moorepants** [comment]
It makes sense to implement this only after we understand this. I think you need to pick Richard's brain about this and then cross reference with questions/docs that show how people handle a single point of failure for a JupyterHub setup. I'll remove from the milestone, but it does sound like we do need to have some way to avoid a single point of failure.

**Comment by moorepants** [comment]
This can be addressed in cluster #2.

**Comment by rkevin-arch** [comment]
Should be resolved by LibreTexts/protogalaxy, since it supports multiple control plane nodes and uses keepalived and HAProxy to loadbalance between them without external nodes.

HA for JupyterHub itself is a different beast, and wouldn't be possible until JupyterHub itself supports running more than one hub simultaneously.
