### ISSUE TITLE
Provide better login error message

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#36]
If someone tries to log in to the hub and has not been whitelisted, they will get a 403 Forbidden page. This page needs to direct them to email us requesting an account (same text as the front page).

**Comment by celine168** [comment]
I just added and tested this feature but I will need to upgrade JupyterHub so the errors will show up. You can see the html page here: https://github.com/LibreTexts/jupyterhub-templates/blob/master/custom/error.html

So far, I have error messages for error codes:
403: redirects them to email/request an account
400 Bad OAuth state: happens when you reload the login callback page(?) after signing in; message redirects user to the home page and try again
500 Internal Server Error: says the problem is on our end, and to email us if the problem persists

JupyterHub already comes with a fitting planet-themed 404 error message.

Also, Luigi and I were joking about adding a funny meme or image to one of the error pages.

**Comment by moorepants** [comment]
These sound good. You have my full support for meme-ifying these pages :)

**Comment by celine168** [comment]
Error pages for errors 403, 400, and 500 are now implemented.
Here's an example:
![image](https://user-images.githubusercontent.com/22624020/65558975-9cc0b080-deed-11e9-8eab-55d834c56dee.png)

**Comment by moorepants** [comment]
Great, no samples of the memes, or I have to discover on my own :)
