### ISSUE TITLE
Implement CI/CD for upgrading helm charts

### ISSUE THREAD

**Issue by lux12337** [LibreTexts/metalc#52]
This would make sure that upgrades for public facing services like JupyterHub and BinderHub experience the minimal amount of complications during configuration upgrades. It would also make sure that upgrades won't break anything.

Some discussion on how Berkeley handles their CI/CD:
* [discourse](https://discourse.jupyter.org/t/ci-cd-solutions/1142?fbclid=IwAR1DKlJHlW1merXQt8_UywsXcF4IDGTx3g8ERGcaWD75dklp5ZNEu3quYL8)

Options for CI/CD with Kubernetes:
* [chartpress](https://github.com/jupyterhub/chartpress?fbclid=IwAR2Bti7rHm3_WKFWXfLLMfxG-E50rRULx1tZ3lqxbn6IlhQLPlfM26afEp8)

**Comment by rkevin-arch** [comment]
IMO CI/CD is only useful for helm charts that we create ourselves (which we don't have any). For services we run like JupyterHub, updates should probably be manual since they are very rare and could introduce breaking changes that need a human in the loop to solve. As for autobuilding the default-env, we have the repo2docker setup that we can easily hook up to Travis or something and build + push the image. If it's the latter, I'd say we can track it over at #123. Celine says this is only for helm charts in that issue, so I think we don't have to leave this open.
