### ISSUE TITLE
Create Onboarding document

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#70]
Drafting here: https://github.com/LibreTexts/metalc/blob/master/docs/Onboarding.md

**Comment by celine168** [comment]
@lux12337 @moorepants Do you think that I'm missing something important?

**Comment by moorepants** [comment]
Needs an explanation on the private repo that contains all the secrets, including ways to keep that safe.

**Comment by moorepants** [comment]
FYI, I added some info about the HR in the onboarding doc.

@tkumar98 and @narrator0 can you all be sure to add info to this doc as you learn new things. Like today you asked "what lab am I in?" "who is the supervisor". Things like that. We should try to add this info to the doc as we figure them out. You two are the best people to do this because you are experiencing the questions now. So as you get answers, they should populate the document.

**Comment by moorepants** [comment]
Closing this.
