### ISSUE TITLE
Create staging branches and document workflow in default-env, jupyter image, jupyter templates

### ISSUE THREAD

**Issue by tannavee** [LibreTexts/metalc#92]
Also, make sure to document the workflow: https://github.com/LibreTexts/metalc/issues/93

**Comment by moorepants** [comment]
What is the status of this issue?

**Comment by celine168** [comment]
This is something we talked about in order to maintain some kind of CI/CD. I don't quite clearly remember the details of this nor did we plan this out thoroughly, but the staging branch would be used to stage things before merging into master (kind of like how the CKEditor plugin works right now).
Looking back, if we want to automate the staging process for these three, we could add a staging branch in which changes to stage for the JupyterHub pages and environment. Ideally, we would have the staging jhub update itself automatically upon pushes to the JupyterHub pages and environment repos. This seems doable, but maybe not high priority.

**Comment by moorepants** [comment]
@LibreTexts/jupyter-team what is the status of this? Do we have our workflow sorted and documented for each relevant repo?

**Comment by TimStewartJ** [comment]
Workflow for jupyter-templates is simple enough since jhub pulls from the repo directly. This isn't explicitly stated anywhere however. Regarding default-env, the current workflow and relationship between dockerhub, github, and tagging is fairly convoluted and definitely needs some reworking (which is something that was mentioned previously by other team members as well). I'm not too sure how to go about doing this, but that's my understanding of the situation right now.

**Comment by moorepants** [comment]
> Workflow for jupyter-templates is simple enough since jhub pulls from the repo directly. This isn't explicitly stated anywhere however.

Maybe add info to the readme of that repository.

> Regarding default-env, the current workflow and relationship between dockerhub, github, and tagging is fairly convoluted and definitely needs some reworking

Start by documenting what we do now.

Double check the documentation in metalc to make sure we haven't written about it before. metalc should contain documentation specific to our cluster and each other repo should contain documentation for working with that particular repo in isolation.

**Comment by TimStewartJ** [comment]
I should clarify that the current default-env workflow actually is documented. I was just mentioning the fact that it's a bit complicated and something we may potentially want to change (which I now realize is already its own issue at #214).

Anyway, I added the workflow info to the jupyterhub-templates repo and made slight changes to the default-env readme since there were several references to the old cluster. I would say this issue is good to close.

**Comment by moorepants** [comment]
Confirmed in meeting that all current repos we use have their workflows documented.
